/**
 * UI strings. English first; Hindi labels for navigation, page titles and
 * main actions (build-prompt §6: "Add Hindi labels if time allows").
 * Missing Hindi keys fall back to English.
 */
export const STRINGS = {
  en: {
    portalName: 'Proof of Life',
    portalSub: 'Pension Life Certificate Portal',
    navHome: 'Home',
    navSubmit: 'Submit Life Certificate',
    navStatus: 'Check Status',
    navPractice: 'Practice Scan',
    navOfficer: 'Officer Login',
    navHow: 'How It Works',
    navHelp: 'Help & FAQs',
    navContact: 'Contact',
    navRegister: 'Register Pensioner',
    navReviews: 'Review Queue',
    navRecords: 'Pensioner Records',
    navTreasury: 'Treasury',
    navLedger: 'Audit Ledger',
    signOut: 'Sign out',
    search: 'Search',
    searchPlaceholder: 'Search the portal',
    accessibility: 'Accessibility',
    textSize: 'Text size',
    helpline: 'Helpline',
    submitCta: 'Submit Life Certificate',
    checkCta: 'Check Status',
    continue: 'Continue',
    tryAgain: 'Try again',
    pensionId: 'Pension ID (PPO number)',
  },
  hi: {
    portalName: 'Proof of Life',
    portalSub: 'पेंशन जीवन प्रमाण पत्र पोर्टल',
    navHome: 'मुख्य पृष्ठ',
    navSubmit: 'जीवन प्रमाण पत्र जमा करें',
    navStatus: 'स्थिति देखें',
    navPractice: 'अभ्यास स्कैन',
    navOfficer: 'अधिकारी लॉगिन',
    navHow: 'यह कैसे काम करता है',
    navHelp: 'सहायता और प्रश्न',
    navContact: 'संपर्क',
    navRegister: 'पेंशनभोगी पंजीकरण',
    navReviews: 'समीक्षा सूची',
    navRecords: 'पेंशनभोगी रिकॉर्ड',
    navTreasury: 'कोषागार',
    navLedger: 'लेखा परीक्षा बही',
    signOut: 'साइन आउट',
    search: 'खोजें',
    searchPlaceholder: 'पोर्टल में खोजें',
    accessibility: 'सुगम्यता',
    textSize: 'अक्षर का आकार',
    helpline: 'हेल्पलाइन',
    submitCta: 'जीवन प्रमाण पत्र जमा करें',
    checkCta: 'स्थिति देखें',
    continue: 'आगे बढ़ें',
    tryAgain: 'फिर से प्रयास करें',
    pensionId: 'पेंशन आईडी (पीपीओ संख्या)',
  },
};
